# Generated by Django 4.1.13 on 2024-08-18 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for part numer', primary_key=True, serialize=False)),
                ('partnumber', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TestResulstAchieve',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for test matrix', primary_key=True, serialize=False)),
                ('serialnumber', models.CharField(db_index=True, max_length=20)),
                ('partnumber', models.CharField(db_index=True, max_length=20)),
                ('fprocess_step', models.CharField(db_index=True, max_length=20)),
                ('station_name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=150)),
                ('evidence_link', models.CharField(max_length=100)),
                ('test_id', models.IntegerField()),
                ('test_name', models.CharField(db_index=True, max_length=100)),
                ('spec_type', models.CharField(max_length=20)),
                ('max_value', models.CharField(max_length=20)),
                ('min_value', models.CharField(max_length=20)),
                ('expected_value', models.CharField(max_length=20)),
                ('result', models.CharField(max_length=20)),
                ('test_time', models.TimeField()),
                ('tc_outcome', models.BooleanField()),
                ('date_created', models.DateTimeField()),
            ],
        ),
    ]
