# Generated by Django 5.0.8 on 2024-08-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for specific test result', primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=15, unique=True)),
                ('product_description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
