# Generated by Django 5.0.8 on 2024-08-15 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowprocessstep',
            name='fprocess_step',
            field=models.CharField(db_index=True, max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z_0-9]*$', 'Only uppercase letters, numbers, and underscores allowed.')]),
        ),
        migrations.AlterField(
            model_name='spectype',
            name='type',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^[A-Z_]*$', 'Only uppercase letters and underscores allowed.')]),
        ),
    ]
