# Generated by Django 5.0.8 on 2024-08-10 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnumber',
            old_name='product_name',
            new_name='partnumber',
        ),
    ]
