# Generated by Django 5.0.8 on 2024-08-13 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tdm', '0002_rename_product_name_partnumber_partnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stations',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for stations', primary_key=True, serialize=False)),
                ('station_family', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='partnumber',
            old_name='product_description',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='id',
            field=models.AutoField(auto_created=True, help_text='ID for part numer', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='partnumber',
            name='partnumber',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='TestPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for test matrix', primary_key=True, serialize=False)),
                ('testplan_name', models.CharField(max_length=20)),
                ('test_id', models.IntegerField()),
                ('test_name', models.CharField(max_length=20)),
                ('spec_type', models.CharField(max_length=10)),
                ('operator', models.CharField(max_length=3)),
                ('expected_value', models.CharField(max_length=20)),
                ('tolerance', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField()),
            ],
            options={
                'unique_together': {('testplan_name', 'test_id')},
            },
        ),
        migrations.CreateModel(
            name='TestMatrix',
            fields=[
                ('id', models.AutoField(auto_created=True, help_text='ID for test matrix', primary_key=True, serialize=False)),
                ('station_family', models.CharField(max_length=20)),
                ('flow_step', models.IntegerField()),
                ('testplan_name', models.CharField(max_length=20)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('date_updated', models.DateTimeField()),
                ('partnumber_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tdm.partnumber')),
            ],
            options={
                'unique_together': {('partnumber_id', 'station_family', 'flow_step')},
            },
        ),
    ]
